import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "../styles/fonts.css";
import Navbar from '../components/Navbar';

const geistSans = Geist({
variable: "--font-geist-sans",
subsets: ["latin"],
});

const geistMono = Geist_Mono({
variable: "--font-geist-mono",
subsets: ["latin"],
});

export const metadata = {
title: "Krishna App",
description: "Generated by Krishna",
};

export default function RootLayout({ children }) {
return (
<html lang="en">
<head>
  <link href="https://fonts.googleapis.com/css2?family=Sansita:ital,wght@0,400;0,700;0,800;0,900;1,400;1,700;1,800;1,900&display=swap" rel="stylesheet" />
  <script src="https://cdn.tailwindcss.com"></script>
</head>
<body className="select-none">
  <div className="min-h-screen bg-gradient-to-br from-gray-900 via-gray-800 to-black text-white">
  <Navbar />
    {children}
  </div>
</body>
</html>
);
}